site_name: GPyEDS

copyright: Copyright (c) 2024 Norbert Toth

theme:
    name: readthedocs
    highlightjs: true

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

nav:
  - GPyEDS: index.md
  - Install: install.md
  - About GPyEDS:
    - Background: background.md
    - Pre-processing: data_preprocess.md
    - Segmentation: segmentation.md
    - Post-processing: post_process.md
    - EDS2CHEM: eds2chem.md
    - How to cite: cite.md
  - Examples:
    - Data Sources for Examples: Examples/Data_sources.md
    - QEMSCAN Data: Examples/QEMSCAN_build_data.ipynb
    - Segmentation: Examples/Segmentation.ipynb
    - EDS2CHEM Calibration: Examples/EDS2CHEM_example.ipynb
  - References:
    - GPAM: references/gpam.md
    - Normalisation: references/mcn.md
    - Neural Network: references/nn.md
    - Spatial Filters: references/spatial_filters.md
    - Utils: references/utils.md
    - EDS2CHEM: references/eds2chem.md
  - Licence:
    Licence: licence.md
